// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.5.2-76-g6a2af82"
#define MICROPY_GIT_HASH "6a2af82"
#define MICROPY_BUILD_DATE "2016-01-21"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (5)
#define MICROPY_VERSION_MICRO (2)
#define MICROPY_VERSION_STRING "1.5.2"
