// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.4.5-19-g65dc960"
#define MICROPY_GIT_HASH "65dc960"
#define MICROPY_BUILD_DATE "2015-08-17"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (4)
#define MICROPY_VERSION_MICRO (5)
#define MICROPY_VERSION_STRING "1.4.5"
